/**
 * Post-publish transpile blazor.webassembly.js for Safari 15+ compatibility.
 *
 * .NET 10's bootloader uses static{} (class static initialization blocks)
 * which Safari 16.4+ requires. Babel's class-static-block plugin transforms
 * it but generates `static #_ = ...` (static private fields), which ALSO
 * requires Safari 16+. This script does a two-step transform:
 *
 *   1. Babel: static{} → static #_ = ...  (removes the SyntaxError)
 *   2. Text post-process: static #_ = ... → direct property assignment
 *      AND removes the helper call + unused parameter
 *
 * Usage: node transpile.js [publish-dir]
 * Default publish dir: ./bin/Release/net10.0/publish
 */

const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');

// ---- Config ----------------------------------------------------------

const publishDir = process.argv[2] || './bin/Release/net10.0/publish';
const blazorJsPath = path.join(
  publishDir,
  'wwwroot',
  '_framework',
  'blazor.webassembly.js'
);

// These are generated by @babel/plugin-transform-class-static-block and
// must be cleaned up afterward because `static #_` (private fields) are
// also unsupported in Safari 15.

const PRIVATE_FIELD_LINE = `static #_ = _staticBlock = () => this.nextEventDelegatorId = 0;`;

// ---- Step 1: Babel transform ----------------------------------------

if (!fs.existsSync(blazorJsPath)) {
  console.error(`[transpile] File not found: ${blazorJsPath}`);
  process.exit(1);
}

const code = fs.readFileSync(blazorJsPath, 'utf8');
const sizeKB = (code.length / 1024).toFixed(1);
console.log(`[transpile] Read ${sizeKB} KB`);

// Step 1A: Transform static{} blocks with Babel
const result = babel.transformSync(code, {
  filename: 'blazor.webassembly.js',
  plugins: ['@babel/plugin-transform-class-static-block'],
  compact: false,
  sourceMaps: false,
});

let output = result.code;
console.log(`[transpile] Babel transform done (${(output.length / 1024).toFixed(1)} KB)`);

// ---- Step 2: Post-process Babel artifacts ---------------------------
// Babel's class-static-block plugin generates:
//   class T { ... static #_ = _staticBlock = () => this.nextEventDelegatorId = 0; }
//   _staticBlock();
// wrapped in: !function (_staticBlock) { ... }()
//
// We need to convert these to Safari-15-compatible forms.

if (output.includes(PRIVATE_FIELD_LINE)) {
  // Step 2A: Babel generates `static #_ = _staticBlock = () => expr; }`
  // followed by `_staticBlock();`. The `}` closes the class.
  // Replace both patterns:
  //
  //   static #_ = _staticBlock = () => this.nextEventDelegatorId = 0;
  //   }
  //   _staticBlock();
  //
  // becomes:
  //   }
  //   T.nextEventDelegatorId = 0;

  output = output.replace(
    PRIVATE_FIELD_LINE + '\n  }\n  _staticBlock();',
    '  }\n  T.nextEventDelegatorId = 0;'
  );

  // Step 2B: Clean up the unused _staticBlock parameter from the outer wrapper
  //   !function (_staticBlock) {  →  !function () {
  output = output.replace(
    '!function (_staticBlock) {',
    '!function () {'
  );

  console.log('[transpile] Post-processed Babel artifacts (private field → assignment)');
} else {
  console.log('[transpile] No private field artifacts found (nothing to post-process)');
}

// ---- Step 3: Verify -------------------------------------------------

const verifications = [
  { pattern: 'static{', name: 'static{} blocks' },
  { pattern: 'static #', name: 'static private fields' },
];
let allClear = true;
for (const { pattern, name } of verifications) {
  if (output.includes(pattern)) {
    console.error(`[transpile] FAIL: ${name} still present after transpilation!`);
    allClear = false;
  }
}

if (allClear) {
  console.log('[transpile] OK: no incompatible syntax remaining.');
}

// ---- Step 4: Write --------------------------------------------------

fs.writeFileSync(blazorJsPath, output, 'utf8');
console.log(`[transpile] Written ${(output.length / 1024).toFixed(1)} KB`);

// Remove stale compressed variants (regenerated on first request)
const brotliPath = blazorJsPath + '.br';
const gzipPath = blazorJsPath + '.gz';
if (fs.existsSync(brotliPath)) { fs.rmSync(brotliPath); console.log('[transpile] Removed stale .br'); }
if (fs.existsSync(gzipPath)) { fs.rmSync(gzipPath); console.log('[transpile] Removed stale .gz'); }

console.log('[transpile] Done.');
